apiVersion: v1
kind: Service
metadata:
  name: cloud-test-service
  namespace: sample
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 5000   
  selector:
    app: cloud-test
